#!/bin/sh
#PBS -l nodes=1:ppn=8,mem=46gb
#PBS -l walltime=476:00:00
#PBS -l cput=9999:00:00
#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -M kiverson@umich.edu
#PBS -q first

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`

~/bin/python/python /share/scratch/khmer/scripts/normalize-by-median.py -k 20 -C 20 -x 1e10 -N 4 -s transcripts.hash cf12_trimmed.unique.fa

echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit

